void main_tex_mod_col_fp(
            float2 diffuse        : TEXCOORD0,
 
            out float4 color    : COLOR,
 
            uniform float4 colorModulate,    // Added the color parameter
            uniform sampler2D texture)
{
    color = tex2D(texture, diffuse);        // Sample the texture
    color = color * colorModulate;            // Multiply the pixel color by colorModulate
    color.a = colorModulate.a;            // Set the output alpha to be colorModulate.w
}
